#! /usr/bin/env bash

script_path=$(dirname $0)

command -v dotfiles && command -v git 

if (($? == 0)) ; then
    dotfiles -R $script_path -C $script_path/dotfilesrc -s
    git submodule update --init --recursive
else
    echo "There was a problem during bootstrap. dotfiles or git is missing"
fi
